### PR TITLE
Restore compatibilty with older versions

### LINKED ISSUE #26: #25 removed compatibility with older dovecot versions
I am running dovecot 2.3.7, as delivered with Ubuntu 20.04 LTS.
This would also hit Debian users on still-supported versions. Debian 10 provides dovecot 2.3.4, Debian 11 provides dovecot 2.3.13.

The fix for enabling compilation against newer dovecot versions broke backwards compatibility:

```
In file included from fts-elastic-plugin.c:11:
fts-elastic-plugin.h:42:52: error: macro "DOVECOT_PREREQ" passed 3 arguments, but takes just 2
   42 | #if defined(DOVECOT_PREREQ) && DOVECOT_PREREQ(2,3,0)
      |                                                    ^
In file included from /usr/include/dovecot/lib.h:27,
                 from fts-elastic-plugin.c:5:
/usr/include/dovecot/macros.h:226: note: macro "DOVECOT_PREREQ" defined here
  226 | #  define DOVECOT_PREREQ(maj, min) \
```

I don't know enough about C to know whether the macro signature could also be checked, to fix it in a way that works for both worlds.
It feels as if the Dovecot team shouldn't have made that change the way they did, at least not in a micro increment.

### LINKED ISSUE #27: call to `fts_mail_user_init`  breaks dovecot backwards compatibility
The signature of `fts_mail_user_init` changed in dovecot 2.3.19: https://github.com/dovecot/core/commit/3eb404aa8ce404580c3028db89202f148a2eda3d#diff-f74a58da5b33812a479395948d05bcf3bf40eee435d63126e081fcad2b34daa1R21

This should be handled gracefully, if a fix for #26 is found.

### PR DESCRIPTION
**Pull request by rpv-tomsk**
Closes: #26
Closes: #27

Checked to compile with 2.2.36 (and run) and 2.3.16/2.3.20 (compile only).

### CODE REVIEW

**Comment by willharris** [comment]
Thanks a lot for this PR!
